<h1>I am in ParcModule DepenceController Indexaction </h1>


<?php var_dump($this->depenses); ?>


<hr />
<table class="table table-bordered table-hover">
	<tr>
		<th>ID</th
		<th>Nature</th>
		<th>Email</th>
		
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($depenses as $depense) { ?>
	<tr>
		<td><?php echo $this->escapeHtml($depense->getIddep());?></td>
		<td><?php echo $this->escapeHtml($depense->getnature());?></td>
		<td><?php echo $this->escapeHtml($depense->getMantant());?></td>
		<td><a href="<?php echo $this->url(NULL,array('controller'=>'Depense', 'action' => 'modifier', 'id'=>$depense->getIddep())); ?>">Edit</a></td>
	    <td><a href="<?php echo $this->url(NULL,array('controller'=>'Depense', 'action' => 'afficher', 'id'=>$depense->getIddep())); ?>">Detail</a></td>
	        <td>
	            <a href="<?php echo $this->url(NULL,array('controller'=>'Depense', 'action' => 'supprimer', 'id'=>$depense->getIddep())); ?>" onclick="return confirm('Are you sure?')">Delete</a>
	        </td>
	       
	</tr>
<?php } ?>
</table>