 <?php if (isset($rep)) : ?>
                <table class="table">
                    <thead>      
                    <tr> 
                       <th>nom</th>
                        <th>annee</th>
                    </tr>
                    </thead>
                <?php foreach($rep as $r): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $r->getNom(); ?></td>
                        <td><?php echo $r->getAnnee(); ?></td>
                        <td> 
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'marque','action'=>'editmarque','id' => $r->getIdmarq()));?>">Edit</a> |
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'marque','action'=>'deletemarque','id' =>$r->getIdmarq()));?>">Delete</a>
                        </td>                                                                                           
                    </tr>
                    </tbody>
            
                <?php endforeach; ?>
                </table>
                <?php endif; ?>