<?php
echo '<h1>Create</h1>';
// $form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...

$form->setAttribute('action', $this->url(NULL,array('controller'=>'Index', 'action' => 'ajouter'))); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();