<?php

$title = 'Edit vehicule';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('vehicules/default',
		array('controller'=>'vehicules', 'action' => 'edit','id'  => $this->id)));

$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<dl >
<dt><?php echo $this->formLabel($form->get('categorie')); ?></dt>
<dd><?php
echo $this->formElement($form->get('categorie'));
echo $this->formElementErrors($form->get('categorie'));
?></dd>
<dt><?php echo $this->formLabel($form->get('modele')); ?></dt>
<dd><?php
echo $this->formElement($form->get('modele'));
echo $this->formElementErrors($form->get('modele'));
?></dd>
<dt><?php echo $this->formLabel($form->get('marque')); ?></dt>
<dd><?php
echo $this->formElement($form->get('marque'));
echo $this->formElementErrors($form->get('marque'));
?></dd>
<dt><?php echo $this->formLabel($form->get('status')); ?></dt>
<dd><?php
echo $this->formElement($form->get('status'));
echo $this->formElementErrors($form->get('status'));
?></dd>
<dt><?php echo $this->formLabel($form->get('matricule')); ?></dt>
<dd><?php
echo $this->formElement($form->get('matricule'));
echo $this->formElementErrors($form->get('matricule'));
?></dd>
<dt><?php echo $this->formLabel($form->get('numchasis')); ?></dt>
<dd><?php
echo $this->formElement($form->get('numchasis'));
echo $this->formElementErrors($form->get('numchasis'));
?></dd>
<dt><?php echo $this->formLabel($form->get('puisfiscal')); ?></dt>
<dd><?php
echo $this->formElement($form->get('puisfiscal'));
echo $this->formElementErrors($form->get('puisfiscal'));
?></dd>
<dt><?php echo $this->formLabel($form->get('datemisecirculation')); ?></dt>
<dd><?php
echo $this->formElement($form->get('datemisecirculation'));
echo $this->formElementErrors($form->get('datemisecirculation'));
?></dd>
<dt><?php echo $this->formLabel($form->get('carburant')); ?></dt>
<dd><?php
echo $this->formElement($form->get('carburant'));
echo $this->formElementErrors($form->get('carburant'));
?></dd>
<dt><?php echo $this->formLabel($form->get('nbreport')); ?></dt>
<dd><?php
echo $this->formElement($form->get('nbreport'));
echo $this->formElementErrors($form->get('nbreport'));
?></dd>
<dt><?php echo $this->formLabel($form->get('option')); ?></dt>
<dd><?php
echo $this->formElement($form->get('option'));
echo $this->formElementErrors($form->get('option'));
?></dd>

<dt><?php echo $this->formLabel($form->get('dernierKm')); ?></dt>
<dd><?php
echo $this->formElement($form->get('dernierKm'));
echo $this->formElementErrors($form->get('dernierKm'));
?></dd>
<dt><?php echo $this->formLabel($form->get('prixachat')); ?></dt>
<dd><?php
echo $this->formElement($form->get('prixachat'));
echo $this->formElementErrors($form->get('prixachat'));
?></dd>
<dt><?php echo $this->formLabel($form->get('concessionnaire')); ?></dt>
<dd><?php
echo $this->formElement($form->get('concessionnaire'));
echo $this->formElementErrors($form->get('concessionnaire'));
?></dd> 
<dt><?php echo $this->formLabel($form->get('souslocation')); ?></dt>
<dd><?php
echo $this->formElement($form->get('souslocation'));
echo $this->formElementErrors($form->get('souslocation'));
?></dd>
<dt><?php echo $this->formLabel($form->get('remarque')); ?></dt>
<dd><?php
echo $this->formElement($form->get('remarque'));
echo $this->formElementErrors($form->get('remarque'));
?></dd>


<dd><?php
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php echo $this->form()->closeTag() ?>

