  <?php if (isset($vehicules)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                    <th>Catégorie</th>
                       <th>Matricule</th>
                       <th>Marque</th>

                       <th> Disponibilité</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($vehicules as $v): ?>
                    <tbody>
                    <tr>
                    <td><a href="<?php echo $this->url('vehicules/default', array('controller'=>'vehicules','action'=>'ind', 'id' => $v->getIdveh()));?>"><?php echo $v->getIdcat()->getIdcat(); ?></a> </td>
                    <td><a href="<?php echo $this->url('vehicules/default', array('controller'=>'vehicules','action'=>'ind', 'id' => $v->getIdveh()));?>"><?php echo $v->getMatricule(); ?></a> </td>
                     <td><a href="<?php echo $this->url('vehicules/default', array('controller'=>'vehicules','action'=>'ind', 'id' => $v->getIdveh()));?>"><?php echo $v->getIdmod()->getNom(); ?></a> </td>
                        
                        <td><a href="<?php echo $this->url('vehicules/default', array('controller'=>'vehicules','action'=>'ind', 'id' => $v->getIdveh()));?>"><?php echo $v->getStatus(); ?></a></td>
                        <td>
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'vehicules','action'=>'edit', 'id' => $v->getIdveh()));?>">Edit</a> |
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'vehicules','action'=>'delete', 'id' => $v->getIdveh()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
