<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Autorisation\Module'                        => __DIR__ . '/Module.php',
    'Autorisation\Controller\AutorisationController' => __DIR__ . '/src/Autorisation/Controller/AutorisationController.php',
    'AutorisationTest\Framework\TestCase'        => __DIR__ . '/tests/Autorisation/Framework/TestCase.php',
    'AutorisationTest\SampleTest'                => __DIR__ . '/tests/Autorisation/SampleTest.php',
);
