<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vehicules\Module'                        => __DIR__ . '/Module.php',
    'Vehicules\Controller\VehiculesController' => __DIR__ . '/src/Vehicules/Controller/VehiculesController.php',
    'VehiculesTest\Framework\TestCase'        => __DIR__ . '/tests/Vehicules/Framework/TestCase.php',
    'VehiculesTest\SampleTest'                => __DIR__ . '/tests/Vehicules/SampleTest.php',
);
