<section class="option">
<h2><?php echo $this->translate('Ajouter une catégorie'); ?></h2>
<?php if ($this->error): ?>
<p class="error">
There were one or more issues with your submission.
Please correct them as
indicated below.
</p>
<?php endif ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,
array('controller'=>'categorie', 'action' => 'addcat')));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('idcat')); ?></dt>
<dd><?php
echo $this->formElement($form->get('idcat'));
echo $this->formElementErrors($form->get('idcat'));
?></dd>

<dt><?php echo $this->formLabel($form->get('prixcat')); ?></dt>
<dd><?php
echo $this->formElement($form->get('prixcat'));
echo $this->formElementErrors($form->get('prixcat'));
?></dd>




<dd><?php
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php echo $this->form()->closeTag() ?>
</section>