 <?php if (isset($rep)) : ?>
                <table class="table">
                    <thead>      
                    <tr> 
                       <th>nom</th>
                        <th>prix</th>
                       
                    </tr>
                    </thead>
                <?php foreach($rep as $r): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $r->getIdcat(); ?></td>
                        <td><?php echo $r->getPrixcat(); ?></td>
                        <td> 
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'categorie','action'=>'editcat','id' => $r->getIdcat()));?>">Edit</a> |
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'categorie','action'=>'deletecat','id' =>$r->getIdcat()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
            
                <?php endforeach; ?>
                </table>
                <?php endif; ?>