<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authentification\Module'                        => __DIR__ . '/Module.php',
    'Authentification\Controller\AuthentificationController' => __DIR__ . '/src/Authentification/Controller/AuthentificationController.php',
    'AuthentificationTest\Framework\TestCase'        => __DIR__ . '/tests/Authentification/Framework/TestCase.php',
    'AuthentificationTest\SampleTest'                => __DIR__ . '/tests/Authentification/SampleTest.php',
);
