
<?php
$form = $this->form;
$form->get('submit')->setValue('Enregistrer');
$form->setAttribute('action', $this->url(NULL,array('controller'=>'Unclient', 'action' => 'fiabilite','id'=>$this->id)));
$form->prepare();
?>
<h3>CLIENT N°:<?php echo $this->id; ?></h3>
<?php 
echo $this->form()->openTag($form);
?>
<h3>Vouler vous changer le statut de ce client</h3>
<dl class="zend_form">
	<dt><?php echo $this->formLabel($form->get('statut')); ?></dt>
	<dd>
	<?php
		echo $this->formElement($form->get('statut'));
		echo $this->formElementErrors($form->get('statut'));
		?>
	</dd>
	
	<dt><?php echo $this->formLabel($form->get('cause')); ?></dt>
	<dd><?php
	echo $this->formElement($form->get('cause'));
	echo $this->formElementErrors($form->get('cause'));
	?>
	</dd>
	</dd>
	
	<dt><?php echo $this->formLabel($form->get('remarque')); ?></dt>
	<dd><?php
	echo $this->formElement($form->get('remarque'));
	echo $this->formElementErrors($form->get('remarque'));
	?>
	</dd>
		<dd><?php
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php 
echo $this->form()->closeTag($form);
	