<section class="option">
<h2><?php echo $this->translate('Ajouter une option'); ?></h2>
<?php if ($this->error): ?>
<p class="error">
There were one or more issues with your submission.
Please correct them as
indicated below.
</p>
<?php endif ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,
array('controller'=>'option', 'action' => 'process')));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
$libellee = $form->get('libellee');
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($libellee); ?></dt>
<dd><?php
echo $this->formElement($libellee);
echo $this->formElementErrors($libellee);
?></dd>
<dt><?php echo $this->formLabel($form->get('remarques')); ?></dt>
<dd><?php
echo $this->formElement($form->get('remarques'));
echo $this->formElementErrors($form->get('remarques'));
?></dd>




<dd><?php
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php echo $this->form()->closeTag() ?>
</section>