<?php
echo '<h1>Update</h1>';
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url(Null, array('controller' => 'autorisation', 'action' => 'modifier', 'id' => $id))); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();