<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Clients\Module'                        => __DIR__ . '/Module.php',
    'Clients\Controller\UnclientController' => __DIR__ . '/src/Clients/Controller/UnclientController.php',
    'ClientsTest\Framework\TestCase'        => __DIR__ . '/tests/Clients/Framework/TestCase.php',
    'ClientsTest\SampleTest'                => __DIR__ . '/tests/Clients/SampleTest.php',
);
