
<?php echo $this->messages; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(NULL, array('controller' => 'Authentification', 'action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
// echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('email'));?><br/>
<?php echo $this->formRow($form->get('password'));?><br/><?php
echo $this->formRow($form->get('rememberme'));?><br/><?php
echo $this->formSubmit($form->get('submit'));?><br/><?php
echo $this->form()->closeTag();
?>

<?php // view helper
    if ($agent = $this->identity()) {
        echo 'Logged in as ' . $this->escapeHtml($agent->getNom());
?>		
 | <a href="<?php echo $this->url(NULL, array('controller' => 'Authentification', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a> 
<br/><br/><br/><br/><br/><br/>
<<ul>
  <li> <a href="<?php echo$this->url('clients/default' , array('controller' => 'UnClient', 'action' => 'Index'));?>">Liste des clients</a> </li>
<li> <a href="<?php echo$this->url('parc/default' , array('controller' => 'Index', 'action' => 'Index'));?>">Liste des agents</a> </li>
<li> <a href="<?php echo$this->url('parc/default' , array('controller' => 'Agence', 'action' => 'Index'));?>">Liste des Agences</a> </li>

  
</ul>

 <?php
    } else {
        echo 'Not logged in';
    }
?>

<p>
	<a href="<?php echo $this->url(NULL , array('controller' => 'Authentification', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>