<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Parc\Module'                        => __DIR__ . '/Module.php',
    'Parc\Controller\IndexController' => __DIR__ . '/src/Parc/Controller/IndexController.php',
    'ParcTest\Framework\TestCase'        => __DIR__ . '/tests/Parc/Framework/TestCase.php',
    'ParcTest\SampleTest'                => __DIR__ . '/tests/Parc/SampleTest.php',
);
