<h1>I am in ParcModule IndexController indexaction </h1>


<?php var_dump($this->agents); ?>


<hr />
<table class="table table-bordered table-hover">
	<tr>
		<th>Nom</th>
		<th>Prenom</th>
		<th>Password</th>
		<th>Email</th>
		<th>Date d'ajout</th>
	</tr>
<?php foreach ($agents as $agent) { ?>
	<tr>
		<td><?php echo $this->escapeHtml($agent->getNom());?></td>
		<td><?php echo $this->escapeHtml($agent->getPrenom());?></td>
		<td><?php echo $this->escapeHtml($agent->getPassword());?></td>
		<td><?php echo $this->escapeHtml($agent->getEmail());?></td>
		<td><?php echo $this->escapeHtml($agent->getDateAjout()->date);?></td>
	</tr>
<?php } ?>
</table>