<h1>I am in ParcModule IndexController indexaction </h1>


<?php 
var_dump($this->agents); 
?>


<hr />
<table class="table table-bordered table-hover">
	<tr>
		<th>Nom</th>
		<th>Prenom</th>
		<th>Password</th>
		<th>Email</th>
		<th>Date d'ajout</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		<th>Autorisation</th>
	</tr>
<?php foreach ($agents as $agent) { ?>
	<tr>
		<td><?php echo $this->escapeHtml($agent->getNom());?></td>
		<td><?php echo $this->escapeHtml($agent->getPrenom());?></td>
		<td><?php echo $this->escapeHtml($agent->getPassword());?></td>
		<td><?php echo $this->escapeHtml($agent->getEmail());?></td>
		<td><?php echo $this->escapeHtml($agent->getDateAjout()->date);?></td>
		<td><a href="<?php echo $this->url(NULL,array('controller'=>'Index', 'action' => 'modifier', 'id'=>$agent->getIdagent())); ?>">Edit</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url(NULL,array('controller'=>'Index', 'action' => 'afficher', 'id'=>$agent->getIdagent())); ?>">Detail</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url(NULL,array('controller'=>'Index', 'action' => 'supprimer', 'id'=>$agent->getIdagent())); ?>" onclick="return confirm('Are you sure?')">Delete</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url(NULL,array('controller'=>'Index', 'action' => 'active', 'id'=>$agent->getIdagent())); ?>">Changer fiabilité</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url('autorisation/default',array('controller'=>'Autorisation', 'action' => 'index', 'id'=>$agent->getIdagent())); ?>">Autorisations</a>
	        </td>
	</tr>
<?php } ?>
</table>