<section class="add">
<h2><?php echo 'Ajouter Incident'; ?></h2>
<?php if ($this->error): ?>
<p class="error">
There were one or more issues with your submission.
Please correct them as
indicated below.
</p>
<?php endif ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,
array('controller'=>'depenses', 'action' => 'addinc','id' => $this->id)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('nrpolice')); ?></dt>
<dd><?php
echo $this->formElement($form->get('nrpolice'));
echo $this->formElementErrors($form->get('nrpolice'));
?></dd>
<dt><?php echo $this->formLabel($form->get("dateincident")); ?></dt>
<dd><?php
echo $this->formElement($form->get("dateincident"));
echo $this->formElementErrors($form->get("dateincident"));
?></dd>
<dt><?php echo $this->formLabel($form->get('expert')); ?></dt>
<dd><?php
echo $this->formElement($form->get('expert'));
echo $this->formElementErrors($form->get('expert'));
?></dd>
<dt><?php echo $this->formLabel($form->get('nrpv')); ?></dt>
<dd><?php
echo $this->formElement($form->get('nrpv'));
echo $this->formElementErrors($form->get('nrpv'));
?></dd>
<dt><?php echo $this->formLabel($form->get('garage')); ?></dt>
<dd><?php
echo $this->formElement($form->get('garage'));
echo $this->formElementErrors($form->get('garage'));
?></dd>
<dt><?php echo $this->formLabel($form->get('remarques')); ?></dt>
<dd><?php
echo $this->formElement($form->get('remarques'));
echo $this->formElementErrors($form->get('remarques'));
?></dd>
<dd><?php
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php echo $this->form()->closeTag() ?>
</section>
