<section class="add">
<h2><?php echo 'Ajouter Réparation'; ?></h2>
<?php if ($this->error): ?>
<p class="error">
There were one or more issues with your submission.
Please correct them as
indicated below.
</p>
<?php endif ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,
array('controller'=>'depenses', 'action' => 'addvisit','id' => $this->id)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('centre')); ?></dt>
<dd><?php
echo $this->formElement($form->get('centre'));
echo $this->formElementErrors($form->get('centre'));
?></dd>
<dt><?php echo $this->formLabel($form->get('datevisite')); ?></dt>
<dd><?php
echo $this->formElement($form->get('datevisite'));
echo $this->formElementErrors($form->get('datevisite'));
?></dd>
<dt><?php echo $this->formLabel($form->get('cordcentre')); ?></dt>
<dd><?php
echo $this->formElement($form->get('cordcentre'));
echo $this->formElementErrors($form->get('cordcentre'));
?></dd>
<dt><?php echo $this->formLabel($form->get("dateexp")); ?></dt>
<dd><?php
echo $this->formElement($form->get("dateexp"));
echo $this->formElementErrors($form->get("dateexp"));
?></dd>
<dt><?php echo $this->formLabel($form->get('montant')); ?></dt>
<dd><?php
echo $this->formElement($form->get('montant'));
echo $this->formElementErrors($form->get('montant'));
?></dd>
<dt><?php echo $this->formLabel($form->get('datepaiement')); ?></dt>
<dd><?php
echo $this->formElement($form->get('datepaiement'));
echo $this->formElementErrors($form->get('datepaiement'));
?></dd>
<dt><?php echo $this->formLabel($form->get('modereg')); ?></dt>
<dd><?php
echo $this->formElement($form->get('modereg'));
echo $this->formElementErrors($form->get('modereg'));
?></dd>
<dt><?php echo $this->formLabel($form->get('numcheq')); ?></dt>
<dd><?php
echo $this->formElement($form->get('numcheq'));
echo $this->formElementErrors($form->get('numcheq'));
?></dd>
<dt><?php echo $this->formLabel($form->get('banque')); ?></dt>
<dd><?php
echo $this->formElement($form->get('banque'));
echo $this->formElementErrors($form->get('banque'));
?></dd>
<dt><?php echo $this->formLabel($form->get('remarque')); ?></dt>
<dd><?php
echo $this->formElement($form->get('remarque'));
echo $this->formElementErrors($form->get('remarque'));
?></dd>
<dd><?php
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php echo $this->form()->closeTag() ?>
</section>
