
<div>
<h3>Ajouter Une Dépense</h3>
</div>
<div>
<br/>

<br/>
<div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addass'));?>">ajouter assurance</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addauto'))?>">ajouter autorisation</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addcarb'));?>">ajouter carburant</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addinc'));?>">ajouter incident</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addpiece'));?>">ajouter piece consommable</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addrep'));?>">ajouter reparation</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addvid'));?>">ajouter vidange</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addvign'));?>">ajouter vignette</a></div>
<br/><div><a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'Addvisit'));?>">ajouter visit techniq</a></div>

</div>