 <?php if (isset($rep)) : ?>
                <table class="table">
                    <thead>
                    <tr> 
                       <th>type</th>
                        <th>typecarb</th>
                        <th>nbrlitre</th>
                        <th>vendeur</th>
                        <th>coovendeur</th>
                        <th>montant</th>
                        <th>datepaiement</th>
                        <th>modereg</th>
                        <th>numcheq</th>
                        <th>banque</th>
                        <th>remarque</th>
                    </tr>
                    </thead>
                <?php foreach($rep as $r): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $r->getType()->format('d/m/Y '); ?></td>
                        <td><?php echo $r->getTypecarb(); ?></td>
                        <td><?php echo $r->getNbrlitre(); ?></td>
                        <td><?php echo $r->getVendeur(); ?></td>
                        <td><?php echo $r->getCoovendeur(); ?></td>
                        <td><?php echo $r->getMontant(); ?></td>
                        <td><?php echo $r->getDatepaiement()->format('d/m/Y '); ?></td>
                        <td><?php echo $r->getModereg(); ?></td>
                        <td><?php echo $r->getNumcheq(); ?></td>
                        <td><?php echo $r->getBanque(); ?></td>
                        <td><?php echo $r->getRemarque(); ?></td>
                        <td> 
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'editCarb','id' => $r->getIdcarb()));?>">Edit</a> |
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'deleteCarb','id' =>$r->getIdcarb()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
            
                <?php endforeach; ?>
                </table>
                <?php endif; ?>