 <?php if (isset($rep)) : ?>
                <table class="table">
                    <thead> 
                    <tr> 
                       <th>datedebut</th>
                        <th>dateexp</th>
                        <th>assureur</th>
                        <th>cordassureur</th>
                        <th>montant</th>
                        <th>datepaiement</th>
                        <th>modereg</th>
                        <th>numcheq</th>
                        <th>banque</th>
                        <th>remarque</th>
                    </tr>
                    </thead>
                <?php foreach($rep as $r): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $r->getDatedebut()->format('d/m/Y '); ?></td>
                        <td><?php echo $r->getDateexp()->format('d/m/Y '); ?></td>
                        <td><?php echo $r->getAssureur(); ?></td>
                        <td><?php echo $r->getCordassureur(); ?></td>
                        <td><?php echo $r->getMontant(); ?></td>
                        <td><?php echo $r->getDatepaiement()->format('d/m/Y '); ?></td>
                        <td><?php echo $r->getModereg(); ?></td>
                        <td><?php echo $r->getNumcheq(); ?></td>
                        <td><?php echo $r->getBanque(); ?></td>
                        <td><?php echo $r->getRemarque(); ?></td>
                        <td> 
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'editass','id' => $r->getIdasc()));?>">Edit</a> |
                            <a href="<?php echo $this->url('vehicules/default', array('controller'=>'depenses','action'=>'deleteass','id' =>$r->getIdasc()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
            
                <?php endforeach; ?>
                </table>
                <?php endif; ?>